### ISSUE TITLE
Ineligible repository

### ISSUE THREAD

**Issue by shanmukhkalasamudram** [aryanthakre/dicee#4]
![Screenshot_1](https://user-images.githubusercontent.com/50857103/95010043-049ef080-0644-11eb-91e1-2e9af215cc14.png)

It is showing that this is an ineligible repository

**Comment by aryanthakre** [comment]
Don't know why? I can't do anything 'cause I'm a participant!

**Comment by aryanthakre** [comment]
Check Now !! I forgot to mention the label !!

**Comment by shanmukhkalasamudram** [comment]
No it's still not working

**Comment by aryanthakre** [comment]
Sorry, Man !! I still dunno what's happening
